strictness: veryhigh
test-warnings: true
doc-warnings: true
max-line-length: 120

ignore-patterns:
    - manage.py
    - hooks/pre-commit

ignore-paths:
    - /migrations/
    - cleanslate_services/

uses:
    - django

pylint:
    run: true
    disable:
        - c-extension-no-member
        - django-not-configured
        - missing-module-docstring
        - missing-timeout
        - too-many-arguments
        - too-many-ancestors
        - too-many-locals
        - too-few-public-methods
        - unsupported-binary-operation
    load-plugins:
        - pylint_django

# style checking
pycodestyle:
    full: true
    options:
        max-line-length: 120

# complexity checking.
mccabe:
    run: true

# checks setup.py
pyroma:
    run: false

# Looks at Python code to search for things which look "dodgy"
# such as passwords or git conflict artifacts
dodgy:
    run: true

# static analysis deprecated in favour of pyflakes
frosted:
    run: false

# docstring checking
pydocstyle:
    run: true
    disable:
        - D100
        - D104
        - D106
        - D107
        - D205
        - D211
        - D212
        - D401

# find unused code.
vulture:
    run: false

# security linter
bandit:
    run: true
    options:
        config: .bandit.yaml

# static analysis
pyflakes:
    run: true

# static typing
mypy:
    run: true
    options:
        strict: true
        follow-imports: false
        python-version: 3.11
