# Generated by Django 4.2 on 2023-04-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fixture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("namespace", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("S", "Stable"),
                            ("U", "Unstable"),
                            ("d", "Deprecated"),
                            ("D", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "db_table": "cleanslate_fixture",
                "abstract": False,
            },
        ),
    ]
