# Generated by Django 4.2 on 2023-04-18 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FixtureDefs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("namespace", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("S", "Stable"),
                            ("U", "Unstable"),
                            ("d", "Deprecated"),
                            ("D", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "cleanslate_fixture_defs",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TestSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.CharField(max_length=200)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Created"),
                            (2, "Starting"),
                            (3, "Started"),
                            (4, "Finishing"),
                            (5, "Finished"),
                        ]
                    ),
                ),
                ("exit_code", models.IntegerField(null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "cleanslate_test_session",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FixtureInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Created"),
                            (2, "Setup Running"),
                            (3, "Setup Finished"),
                            (4, "Setup Failed"),
                            (5, "Teardown Running"),
                            (6, "Teardown Finished"),
                            (7, "Teardown Failed"),
                        ]
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "fixture_def_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fixture.fixturedefs",
                    ),
                ),
                (
                    "session_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fixture.testsession",
                    ),
                ),
            ],
            options={
                "db_table": "cleanslate_fixture_instances",
                "abstract": False,
            },
        ),
    ]
