# Generated by Django 4.2 on 2023-04-19 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fixture", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixturedefs",
            name="fixture_type",
            field=models.IntegerField(
                choices=[
                    (1, "Fixture Internal"),
                    (2, "Fixture Github"),
                    (3, "Fixture Docker"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fixtureinstance",
            name="fixture_def_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fixture.fixturedefs",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fixturedefs",
            unique_together={("namespace", "name")},
        ),
    ]
