# Generated by Django 4.2 on 2023-04-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fixture", "0002_fixturedefs_fixture_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixtureinstance",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
