# Generated by Django 4.2 on 2023-04-30 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fixture", "0005_resourcecontent_resource"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TestSession",
            new_name="Session",
        ),
        migrations.AlterField(
            model_name="resource",
            name="content",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fixture.resourcecontent",
            ),
        ),
        migrations.AlterModelTable(
            name="session",
            table="cleanslate_session",
        ),
    ]
