# Generated by Django 4.2 on 2023-05-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fixture", "0007_alter_fixtureinstance_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Created"),
                    (2, "Starting"),
                    (3, "Started"),
                    (4, "Finishing"),
                    (5, "Finished"),
                    (6, "Error"),
                ]
            ),
        ),
    ]
